export const GET_ZIPDATA_REQUEST = "GET_ZIPDATA_REQUEST";
export const GET_ZIPDATA_SUCCESS = "GET_ZIPDATA_SUCCESS";
export const GET_ZIPDATA_FAILURE = "GET_ZIPDATA_FAILURE";

export const RESET_DATA_REQUEST = "RESET_DATA_REQUEST";
export const RESET_DATA = "RESET_DATA";
